/*
    Run on Snowflake
*/

USE WAREHOUSE COMPUTE_WH;
USE ROLE SYSADMIN;

USE DATABASE DEMODB_PGMIRROR;
USE SCHEMA DEMO;

DROP AGENT DEMODB_PGMIRROR.DEMO.IOT_AGENT_DEMO;
CALL SNOWFLAKE.POSTGRES.LIST_MIRRORED_TABLES('iot_mirror');
CALL SNOWFLAKE.POSTGRES.DROP_MIRROR(mirror_name => 'iot_mirror', drop_target_database => TRUE);

SHOW DATABASES LIKE 'DEMO%';

--DROP DATABASE DEMODB;

SHOW WAREHOUSES LIKE 'DEMO%';

--DROP WAREHOUSE DEMO_IW;