-- LINEITEM_DASHBOARD: LINEITEM denormalized with customer market segment and region.
-- Run against an existing TPC-H interactive schema (LINEITEM, ORDERS, CUSTOMER, NATION, REGION).
-- Replace {{SCALE}} with the target scale factor (1, 10, 100, or 1000).

USE ROLE SYSADMIN;
USE DATABASE IW_TPCH_BENCH;

-- Set the schema to the target scale factor (TPCH_SF{{SCALE}})
USE SCHEMA TPCH_SF{{SCALE}};

-- Set the warehouse to the target scale factor (TPCH_BENCH_WH_{{SCALE}})
USE WAREHOUSE TPCH_BENCH_WH_{{SCALE}};

-- Create the standard table (LINEITEM_DASHBOARD)
CREATE OR REPLACE TABLE LINEITEM_DASHBOARD CLUSTER BY (L_SHIPDATE)(
	L_ORDERKEY NUMBER(38,0) NOT NULL,
	L_PARTKEY NUMBER(38,0),
	L_SUPPKEY NUMBER(38,0),
	L_LINENUMBER NUMBER(38,0) NOT NULL,
	L_QUANTITY NUMBER(15,2),
	L_EXTENDEDPRICE NUMBER(15,2),
	L_DISCOUNT NUMBER(15,2),
	L_TAX NUMBER(15,2),
	L_RETURNFLAG VARCHAR(1),
	L_LINESTATUS VARCHAR(1),
	L_SHIPDATE DATE,
	L_COMMITDATE DATE,
	L_RECEIPTDATE DATE,
	L_SHIPINSTRUCT VARCHAR(25),
	L_SHIPMODE VARCHAR(10),
	L_COMMENT VARCHAR(44),
	L_MKTSEGMENT VARCHAR(10),
	L_REGIONNAME VARCHAR(25),
	L_CUSTKEY NUMBER(38,0),
	L_ORDERSTATUS VARCHAR(1),
	PRIMARY KEY (L_ORDERKEY, L_LINENUMBER) RELY
) AS
SELECT
	l.L_ORDERKEY,
	l.L_PARTKEY,
	l.L_SUPPKEY,
	l.L_LINENUMBER,
	l.L_QUANTITY,
	l.L_EXTENDEDPRICE,
	l.L_DISCOUNT,
	l.L_TAX,
	l.L_RETURNFLAG,
	l.L_LINESTATUS,
	l.L_SHIPDATE,
	l.L_COMMITDATE,
	l.L_RECEIPTDATE,
	l.L_SHIPINSTRUCT,
	l.L_SHIPMODE,
	l.L_COMMENT,
	c.C_MKTSEGMENT AS L_MKTSEGMENT,
	r.R_NAME AS L_REGIONNAME,
	o.O_CUSTKEY AS L_CUSTKEY,
	o.O_ORDERSTATUS AS L_ORDERSTATUS
FROM LINEITEM l
JOIN ORDERS o ON o.O_ORDERKEY = l.L_ORDERKEY
JOIN CUSTOMER c ON c.C_CUSTKEY = o.O_CUSTKEY
JOIN NATION n ON n.N_NATIONKEY = c.C_NATIONKEY
JOIN REGION r ON r.R_REGIONKEY = n.N_REGIONKEY
ORDER BY l.L_SHIPDATE;

-- Set the schema to the target scale factor (TPCH_SF{{SCALE}}_IT)
USE SCHEMA TPCH_SF{{SCALE}}_IT;

-- Create the interactive table (LINEITEM_DASHBOARD in TPCH_SF{{SCALE}}_IT)
CREATE OR REPLACE INTERACTIVE TABLE LINEITEM_DASHBOARD CLUSTER BY (L_SHIPDATE)(
	L_ORDERKEY NUMBER(38,0) NOT NULL,
	L_PARTKEY NUMBER(38,0),
	L_SUPPKEY NUMBER(38,0),
	L_LINENUMBER NUMBER(38,0) NOT NULL,
	L_QUANTITY NUMBER(15,2),
	L_EXTENDEDPRICE NUMBER(15,2),
	L_DISCOUNT NUMBER(15,2),
	L_TAX NUMBER(15,2),
	L_RETURNFLAG VARCHAR(1),
	L_LINESTATUS VARCHAR(1),
	L_SHIPDATE DATE,
	L_COMMITDATE DATE,
	L_RECEIPTDATE DATE,
	L_SHIPINSTRUCT VARCHAR(25),
	L_SHIPMODE VARCHAR(10),
	L_COMMENT VARCHAR(44),
	L_MKTSEGMENT VARCHAR(10),
	L_REGIONNAME VARCHAR(25),
	L_CUSTKEY NUMBER(38,0),
	L_ORDERSTATUS VARCHAR(1),
	PRIMARY KEY (L_ORDERKEY, L_LINENUMBER) RELY
) AS
SELECT
	*
FROM TPCH_SF{{SCALE}}.LINEITEM_DASHBOARD
ORDER BY L_SHIPDATE;
