CREATE DATABASE CONCURRENCY_DEMO_DB;
CREATE SCHEMA CONCURRENCY_DEMO_DB.DEMO;
CREATE WAREHOUSE DEMO_STANDARD_XS WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE STATEMENT_TIMEOUT_IN_SECONDS = 60 STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 30;
CREATE INTERACTIVE WAREHOUSE DEMO_INTERACTIVE_XS WAREHOUSE_SIZE = XSMALL MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 AUTO_SUSPEND = 86400 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE STATEMENT_TIMEOUT_IN_SECONDS = 5 STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 30;
CREATE RESOURCE MONITOR CONCURRENCY_DEMO_MONITOR WITH CREDIT_QUOTA = 10 FREQUENCY = NEVER START_TIMESTAMP = IMMEDIATELY TRIGGERS ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE DEMO_STANDARD_XS SET RESOURCE_MONITOR = CONCURRENCY_DEMO_MONITOR;
ALTER WAREHOUSE DEMO_INTERACTIVE_XS SET RESOURCE_MONITOR = CONCURRENCY_DEMO_MONITOR;
USE WAREHOUSE DEMO_STANDARD_XS;
CREATE TRANSIENT TABLE CONCURRENCY_DEMO_DB.DEMO.SALES AS
WITH numbered AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS sale_id
  FROM TABLE(GENERATOR(ROWCOUNT => 10000000))
), dimensions AS (
  SELECT sale_id,
    DATEADD(day, MOD(ABS(HASH(sale_id, 'date')), 365), '2025-01-01'::DATE)::DATE AS sale_date,
    (1 + MOD(ABS(HASH(sale_id, 'region')), 8))::INTEGER AS region_id,
    (1 + MOD(ABS(HASH(sale_id, 'product')), 2000))::INTEGER AS product_id,
    (1 + MOD(ABS(HASH(sale_id, 'quantity')), 5))::INTEGER AS quantity,
    ((500 + MOD(ABS(HASH(sale_id, 'price')), 49500)) / 100)::NUMBER(12,2) AS unit_price
  FROM numbered
)
SELECT sale_id, sale_date, region_id, product_id,
  MOD(product_id - 1, 8)::INTEGER AS category_id, quantity,
  (quantity * unit_price)::NUMBER(14,2) AS revenue
FROM dimensions
ORDER BY region_id, sale_date;
ALTER WAREHOUSE DEMO_INTERACTIVE_XS ADD TABLES (CONCURRENCY_DEMO_DB.DEMO.SALES);
CREATE ROLE CONCURRENCY_DEMO_APP;
GRANT ROLE CONCURRENCY_DEMO_APP TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE CONCURRENCY_DEMO_DB TO ROLE CONCURRENCY_DEMO_APP;
GRANT USAGE ON SCHEMA CONCURRENCY_DEMO_DB.DEMO TO ROLE CONCURRENCY_DEMO_APP;
GRANT SELECT ON TABLE CONCURRENCY_DEMO_DB.DEMO.SALES TO ROLE CONCURRENCY_DEMO_APP;
GRANT USAGE, MONITOR, OPERATE ON WAREHOUSE DEMO_STANDARD_XS TO ROLE CONCURRENCY_DEMO_APP;
GRANT USAGE, MONITOR, OPERATE ON WAREHOUSE DEMO_INTERACTIVE_XS TO ROLE CONCURRENCY_DEMO_APP;
GRANT USAGE ON DATABASE SNOWFLAKE_APPS TO ROLE CONCURRENCY_DEMO_APP;
GRANT USAGE, CREATE APPLICATION SERVICE, CREATE ARTIFACT REPOSITORY, CREATE STAGE ON SCHEMA SNOWFLAKE_APPS.PUBLIC TO ROLE CONCURRENCY_DEMO_APP;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_APPS_QUERY_WH TO ROLE CONCURRENCY_DEMO_APP;
