"""Render Cube's and the web app's environment files from the TOML .env.

`.env` is the single source of truth (see .env.example). This script writes:

    .env.cube               consumed by docker-compose, and inlined into the
                            container spec by render_spec.py
    cube/model/cubes.js     rendered from cube/cubes.template.js

Both outputs are gitignored. The model is rendered rather than reading env at
runtime because Cube's model sandbox exposes neither `process`, `require` nor
`module`, and top-level consts are not shared between model files - so rendering
is the only way to keep database names out of the committed source.

Nothing here is committed: .env.cube holds the Snowflake PAT and the Postgres
password, and is gitignored.

Usage (from bi_dashboard/):
    uv run gen_env.py
"""

import secrets
import re
from pathlib import Path

import config

HERE = Path(__file__).parent
OUT = HERE / ".env.cube"
TEMPLATE = HERE / "cube" / "cubes.template.js"
MODEL = HERE / "cube" / "model" / "cubes.js"

MARKER = "// __TABLES__"


def render_model(tables: dict[str, str]) -> None:
    """Renders cube/model/cubes.js from the template, injecting table names."""
    src = TEMPLATE.read_text()
    if MARKER not in src:
        raise SystemExit(f"{TEMPLATE} no longer contains the {MARKER} marker")

    entries = "\n".join(f"  {k}: '{v}'," for k, v in tables.items())
    block = (
        "// Generated from ../cubes.template.js by gen_env.py - do not edit.\n"
        "const TABLES = {\n"
        f"{entries}\n"
        "};"
    )
    # Drop the marker's explanatory comment lines along with the marker itself.
    lines, out, skipping = src.splitlines(), [], False
    for line in lines:
        if line.strip() == MARKER:
            out.append(block)
            skipping = True
            continue
        if skipping:
            if line.startswith("//") or not line.strip():
                if not line.strip():
                    skipping = False
                continue
            skipping = False
        out.append(line)

    MODEL.parent.mkdir(parents=True, exist_ok=True)
    MODEL.write_text("\n".join(out) + "\n")


def main() -> None:
    cfg = config.load()
    token = config.read_token(cfg)

    # Generated rather than stored, so no shared secret lives in the repo. The web
    # container reads the same value to sign its proxy requests.
    api_secret = secrets.token_hex(32)

    fact = config.fqn(cfg, "fact_table")
    product = config.fqn(cfg, "dim_product_table")
    user_tbl = config.fqn(cfg, "dim_user_table")

    pg_schema = cfg["pg_schema"]
    concurrency = cfg["tile_concurrency"]

    lines = [
        "# Generated by gen_env.py from ../.env - do not edit by hand.",
        "CUBEJS_DEV_MODE=true",
        "CUBEJS_LOG_LEVEL=info",
        f"CUBEJS_API_SECRET={api_secret}",
        # Pre-aggregations are deliberately off: the point is to compare raw engine
        # latency, not Cube's cache.
        "CUBEJS_PRE_AGGREGATIONS_SCHEMA=",
        "CUBEJS_SCHEDULED_REFRESH_DEFAULT=false",
        "",
        # Required: the decorated CUBEJS_DS_<NAME>_* vars below are ignored unless
        # the data source is declared here. "default" must be present even though no
        # cube uses it, or Cube raises "The default data source is missing in the
        # declared CUBEJS_DATASOURCES". It mirrors the Snowflake connection.
        "CUBEJS_DATASOURCES=default,sf,pg",
        "",
        # The dashboard fires one query per tile, all at once. Cube's driver pool
        # defaults to 8, so tiles queue and the latency badge reports the wait
        # rather than the engine. Set identically on both sources so neither side
        # is penalised by queueing.
        f"CUBEJS_CONCURRENCY={concurrency}",
        "",
        "# --- default (unused by any cube; mirrors sf) ---",
        "CUBEJS_DB_TYPE=snowflake",
        f"CUBEJS_DB_SNOWFLAKE_ACCOUNT={cfg['account']}",
        f"CUBEJS_DB_USER={cfg['user']}",
        f"CUBEJS_DB_PASS={token}",
        f"CUBEJS_DB_SNOWFLAKE_AUTHENTICATOR={cfg['authenticator']}",
        f"CUBEJS_DB_SNOWFLAKE_ROLE={cfg['role']}",
        f"CUBEJS_DB_SNOWFLAKE_WAREHOUSE={cfg['interactive_warehouse']}",
        f"CUBEJS_DB_NAME={cfg['bi_database']}",
        f"CUBEJS_DB_SCHEMA={cfg['bi_schema']}",
        "",
        "# --- dataSource: sf (Snowflake) ---",
        "CUBEJS_DS_SF_DB_TYPE=snowflake",
        f"CUBEJS_DS_SF_DB_SNOWFLAKE_ACCOUNT={cfg['account']}",
        f"CUBEJS_DS_SF_DB_USER={cfg['user']}",
        f"CUBEJS_DS_SF_DB_PASS={token}",
        f"CUBEJS_DS_SF_DB_SNOWFLAKE_AUTHENTICATOR={cfg['authenticator']}",
        f"CUBEJS_DS_SF_DB_SNOWFLAKE_ROLE={cfg['role']}",
        f"CUBEJS_DS_SF_DB_SNOWFLAKE_WAREHOUSE={cfg['interactive_warehouse']}",
        f"CUBEJS_DS_SF_DB_NAME={cfg['bi_database']}",
        f"CUBEJS_DS_SF_DB_SCHEMA={cfg['bi_schema']}",
        f"CUBEJS_DS_SF_DB_MAX_POOL={concurrency}",
        "",
        "# --- dataSource: pg (Postgres) ---",
        "CUBEJS_DS_PG_DB_TYPE=postgres",
        f"CUBEJS_DS_PG_DB_HOST={cfg['PGHOST']}",
        f"CUBEJS_DS_PG_DB_PORT={cfg['PGPORT']}",
        f"CUBEJS_DS_PG_DB_USER={cfg['PGUSER']}",
        f"CUBEJS_DS_PG_DB_PASS={cfg['PGPASSWORD']}",
        f"CUBEJS_DS_PG_DB_NAME={cfg['PGDATABASE']}",
        f"CUBEJS_DS_PG_DB_SCHEMA={pg_schema}",
        f"CUBEJS_DS_PG_DB_SSL={'true' if cfg['pg_ssl'] else 'false'}",
        f"CUBEJS_DS_PG_DB_MAX_POOL={concurrency}",
        "",
        "# --- web app ---",
        # NEXT_PUBLIC_* is inlined into the browser bundle at build time, so these
        # must be present when `npm run build` runs, not only at runtime.
        f"NEXT_PUBLIC_DATA_START={cfg['data_start']}",
        f"NEXT_PUBLIC_DATA_END={cfg['data_end']}",
        f"NEXT_PUBLIC_DATA_END_TS={cfg['data_end_ts']}",
        "",
    ]

    OUT.write_text("\n".join(lines))
    OUT.chmod(0o600)
    print(f"Wrote {OUT}")

    render_model(
        {
            "SF_FACT": fact,
            "SF_PRODUCT": product,
            "SF_USER": user_tbl,
            "PG_FACT": f"{pg_schema}.purchase_transactions",
            "PG_PRODUCT": f"{pg_schema}.product_catalog",
            "PG_USER": f"{pg_schema}.user_dimensions",
        }
    )
    print(f"Wrote {MODEL}")
    print("Cube data sources: sf -> " + fact)
    print("                   pg -> " + f"{pg_schema}.purchase_transactions")


if __name__ == "__main__":
    main()
