"""Render deployment manifests from .env.

Two outputs, both gitignored because they contain the Snowflake PAT and the
Postgres password:

    .spcs-spec.rendered.yaml    Snowpark Container Services service spec
    .k8s.rendered.yaml          Kubernetes Deployment + Service + Secret

Credentials are injected at deploy time rather than baked into an image layer, so
the images stay free of secrets and can be rebuilt without them.

Usage (from bi_dashboard/):
    uv run gen_env.py && uv run render_spec.py            # SPCS
    uv run gen_env.py && uv run render_spec.py --target k8s
"""

import argparse
import base64
from pathlib import Path

import config

HERE = Path(__file__).parent
ENV_CUBE = HERE / ".env.cube"

# The web container needs the Cube API secret to sign its proxy requests, and the
# NEXT_PUBLIC_* values at build time. Everything else belongs to Cube alone.
WEB_KEYS = {"CUBEJS_API_SECRET"}

CUBE_PORT = 4000
WEB_PORT = 3000


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        raise SystemExit(f"{path} not found - run `uv run gen_env.py` first")
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        if v.strip():
            out[k.strip()] = v.strip()
    return out


def yaml_scalar(v: str) -> str:
    """Quote every value: PATs and generated passwords routinely contain
    characters (:, #, leading digits) that YAML would otherwise reinterpret."""
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_spcs(cfg: dict, env: dict[str, str]) -> str:
    repo = cfg["image_repo"].rstrip("/")
    cube_env = "\n".join(
        f"        {k}: {yaml_scalar(v)}" for k, v in sorted(env.items())
    )
    web_env = "\n".join(
        f"        {k}: {yaml_scalar(env[k])}" for k in sorted(WEB_KEYS) if env.get(k)
    )
    return f"""# Generated by render_spec.py from ../.env - do not edit, do not commit.
spec:
  containers:
    - name: cube
      image: {repo}/bi-cube:latest
      env:
{cube_env}
      resources:
        requests:
          memory: 2Gi
          cpu: 1
        limits:
          memory: 4Gi
          cpu: 2

    - name: web
      image: {repo}/bi-web:latest
      env:
        CUBE_API_URL: "http://localhost:{CUBE_PORT}/cubejs-api/v1"
{web_env}
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 1

  endpoints:
    # Only the web app is public. Cube stays internal: it holds the Snowflake
    # credential and the Postgres password.
    - name: web
      port: {WEB_PORT}
      public: true
"""


def render_k8s(cfg: dict, env: dict[str, str]) -> str:
    registry = cfg.get("image_registry", "").rstrip("/")
    repo = cfg["image_repo"].strip("/")
    prefix = f"{registry}/{repo}" if registry else repo

    secret_data = "\n".join(
        f"  {k}: {base64.b64encode(v.encode()).decode()}" for k, v in sorted(env.items())
    )
    return f"""# Generated by render_spec.py from ../.env - do not edit, do not commit.
#
# Both containers share a Pod so the web app reaches Cube on localhost, matching
# the SPCS layout. Only the web port is exposed by the Service.
apiVersion: v1
kind: Secret
metadata:
  name: bi-dashboard-env
type: Opaque
data:
{secret_data}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bi-dashboard
  template:
    metadata:
      labels:
        app: bi-dashboard
    spec:
      containers:
        - name: cube
          image: {prefix}/bi-cube:latest
          envFrom:
            - secretRef:
                name: bi-dashboard-env
          ports:
            - containerPort: {CUBE_PORT}
          resources:
            requests:
              memory: 2Gi
              cpu: "1"
            limits:
              memory: 4Gi
              cpu: "2"
        - name: web
          image: {prefix}/bi-web:latest
          env:
            - name: CUBE_API_URL
              value: "http://localhost:{CUBE_PORT}/cubejs-api/v1"
            - name: CUBEJS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: bi-dashboard-env
                  key: CUBEJS_API_SECRET
          ports:
            - containerPort: {WEB_PORT}
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: bi-dashboard
spec:
  # LoadBalancer is the quickest thing that works on EKS/GKE/AKS. Put an Ingress
  # in front of it if you need TLS or authentication -- note that unlike an SPCS
  # public endpoint, nothing here authenticates users for you.
  type: LoadBalancer
  selector:
    app: bi-dashboard
  ports:
    - port: 80
      targetPort: {WEB_PORT}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=["spcs", "k8s"], default="spcs")
    args = ap.parse_args()

    cfg = config.load()
    env = parse_env_file(ENV_CUBE)

    if args.target == "spcs":
        out, body = HERE / ".spcs-spec.rendered.yaml", render_spcs(cfg, env)
    else:
        out, body = HERE / ".k8s.rendered.yaml", render_k8s(cfg, env)

    out.write_text(body)
    out.chmod(0o600)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
