-- TPC-H iceberg tables setup (per scale factor)
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS {{SOLUTION_NAME}}_BENCH_DB;
USE DATABASE {{SOLUTION_NAME}}_BENCH_DB;

CREATE SCHEMA IF NOT EXISTS TPCH_SF{{SCALE}}_ICE;
USE SCHEMA TPCH_SF{{SCALE}}_ICE;

CREATE OR REPLACE WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_LOAD
  WAREHOUSE_SIZE = '{{LOAD_WH_SIZE}}'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE;

USE WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_LOAD;

CREATE OR REPLACE ICEBERG TABLE LINEITEM
  CLUSTER BY (L_SHIPDATE)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '{{EXTERNAL_VOLUME}}'
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.LINEITEM;

CREATE OR REPLACE ICEBERG TABLE ORDERS
  CLUSTER BY (O_ORDERDATE)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '{{EXTERNAL_VOLUME}}'
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.ORDERS;

CREATE OR REPLACE ICEBERG TABLE CUSTOMER
  CLUSTER BY (C_CUSTKEY)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '{{EXTERNAL_VOLUME}}'
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.CUSTOMER;

CREATE OR REPLACE ICEBERG TABLE PART
  CLUSTER BY (P_PARTKEY)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '{{EXTERNAL_VOLUME}}'
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PART;

CREATE OR REPLACE ICEBERG TABLE PARTSUPP
  CLUSTER BY (PS_PARTKEY)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '{{EXTERNAL_VOLUME}}'
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PARTSUPP;

CREATE OR REPLACE ICEBERG TABLE SUPPLIER
  CLUSTER BY (S_SUPPKEY)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '{{EXTERNAL_VOLUME}}'
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.SUPPLIER;

CREATE OR REPLACE ICEBERG TABLE NATION
  CLUSTER BY (N_NATIONKEY)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '{{EXTERNAL_VOLUME}}'
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.NATION;

CREATE OR REPLACE ICEBERG TABLE REGION
  CLUSTER BY (R_REGIONKEY)
  CATALOG = 'SNOWFLAKE'
  EXTERNAL_VOLUME = '{{EXTERNAL_VOLUME}}'
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.REGION;

DROP WAREHOUSE IF EXISTS {{SOLUTION_NAME}}_BENCH_WH_LOAD;
