-- TPC-H standard warehouse setup (per scale factor)
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS {{SOLUTION_NAME}}_BENCH_WH_STD_{{SCALE}}
  WAREHOUSE_SIZE = '{{BENCH_WH_SIZE}}'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
