-- TPC-H interactive warehouse setup (per scale factor)
-- Requires: standard warehouse (for fallback) and interactive tables already created.
USE ROLE SYSADMIN;

CREATE OR REPLACE INTERACTIVE WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_INT_{{SCALE}}
  TABLES (
    {{SOLUTION_NAME}}_BENCH_DB.{{SCHEMA_NAME}}.LINEITEM,
    {{SOLUTION_NAME}}_BENCH_DB.{{SCHEMA_NAME}}.ORDERS,
    {{SOLUTION_NAME}}_BENCH_DB.{{SCHEMA_NAME}}.CUSTOMER,
    {{SOLUTION_NAME}}_BENCH_DB.{{SCHEMA_NAME}}.PART,
    {{SOLUTION_NAME}}_BENCH_DB.{{SCHEMA_NAME}}.PARTSUPP,
    {{SOLUTION_NAME}}_BENCH_DB.{{SCHEMA_NAME}}.SUPPLIER,
    {{SOLUTION_NAME}}_BENCH_DB.{{SCHEMA_NAME}}.NATION,
    {{SOLUTION_NAME}}_BENCH_DB.{{SCHEMA_NAME}}.REGION
  )
  WAREHOUSE_SIZE = '{{BENCH_WH_SIZE}}';
ALTER WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_INT_{{SCALE}} RESUME IF SUSPENDED;
ALTER WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_INT_{{SCALE}} SET FALLBACK_WAREHOUSE = {{SOLUTION_NAME}}_BENCH_WH_STD_{{SCALE}};
