-- TPC-H interactive tables setup (per scale factor)
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS {{SOLUTION_NAME}}_BENCH_DB;
USE DATABASE {{SOLUTION_NAME}}_BENCH_DB;

CREATE SCHEMA IF NOT EXISTS TPCH_SF{{SCALE}}_IT;
USE SCHEMA TPCH_SF{{SCALE}}_IT;

CREATE OR REPLACE WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_LOAD
  WAREHOUSE_SIZE = '{{LOAD_WH_SIZE}}'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE;

USE WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_LOAD;

-- Clustering keys derived from query analysis (see README.md).

CREATE OR REPLACE INTERACTIVE TABLE CUSTOMER CLUSTER BY (C_CUSTKEY)(
	C_CUSTKEY NUMBER(38,0) NOT NULL,
	C_NAME VARCHAR(25),
	C_ADDRESS VARCHAR(40),
	C_NATIONKEY NUMBER(38,0),
	C_PHONE VARCHAR(15),
	C_ACCTBAL NUMBER(15,2),
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117),
    PRIMARY KEY (C_CUSTKEY) RELY
) AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.CUSTOMER ORDER BY C_CUSTKEY;

CREATE OR REPLACE INTERACTIVE TABLE NATION CLUSTER BY (N_NATIONKEY)(
	N_NATIONKEY NUMBER(38,0) NOT NULL,
	N_NAME VARCHAR(25),
	N_REGIONKEY NUMBER(38,0),
	N_COMMENT VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY) RELY
) AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.NATION ORDER BY N_NATIONKEY;

CREATE OR REPLACE INTERACTIVE TABLE ORDERS CLUSTER BY (O_ORDERDATE)(
	O_ORDERKEY NUMBER(38,0) NOT NULL,
	O_CUSTKEY NUMBER(38,0),
	O_ORDERSTATUS VARCHAR(1),
	O_TOTALPRICE NUMBER(15,2),
	O_ORDERDATE DATE,
	O_ORDERPRIORITY VARCHAR(15),
	O_CLERK VARCHAR(15),
	O_SHIPPRIORITY NUMBER(38,0),
	O_COMMENT VARCHAR(79),
    PRIMARY KEY (O_ORDERKEY) RELY
) AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.ORDERS ORDER BY O_ORDERDATE;

CREATE OR REPLACE INTERACTIVE TABLE PART CLUSTER BY (P_PARTKEY)(
	P_PARTKEY NUMBER(38,0) NOT NULL,
	P_NAME VARCHAR(55),
	P_MFGR VARCHAR(25),
	P_BRAND VARCHAR(10),
	P_TYPE VARCHAR(25),
	P_SIZE NUMBER(38,0),
	P_CONTAINER VARCHAR(10),
	P_RETAILPRICE NUMBER(15,2),
	P_COMMENT VARCHAR(23),
    PRIMARY KEY (P_PARTKEY) RELY
) AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PART ORDER BY P_PARTKEY;

CREATE OR REPLACE INTERACTIVE TABLE PARTSUPP CLUSTER BY (PS_PARTKEY)(
	PS_PARTKEY NUMBER(38,0) NOT NULL,
	PS_SUPPKEY NUMBER(38,0) NOT NULL,
	PS_AVAILQTY NUMBER(38,0),
	PS_SUPPLYCOST NUMBER(15,2),
	PS_COMMENT VARCHAR(199),
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY) RELY
) AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PARTSUPP ORDER BY PS_PARTKEY;

CREATE OR REPLACE INTERACTIVE TABLE REGION CLUSTER BY (R_REGIONKEY)(
	R_REGIONKEY NUMBER(38,0) NOT NULL,
	R_NAME VARCHAR(25),
	R_COMMENT VARCHAR(152),
    PRIMARY KEY (R_REGIONKEY) RELY
) AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.REGION ORDER BY R_REGIONKEY;

CREATE OR REPLACE INTERACTIVE TABLE SUPPLIER CLUSTER BY (S_SUPPKEY)(
	S_SUPPKEY NUMBER(38,0) NOT NULL,
	S_NAME VARCHAR(25),
	S_ADDRESS VARCHAR(40),
	S_NATIONKEY NUMBER(38,0),
	S_PHONE VARCHAR(15),
	S_ACCTBAL NUMBER(15,2),
	S_COMMENT VARCHAR(101),
    PRIMARY KEY (S_SUPPKEY) RELY
) AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.SUPPLIER ORDER BY S_SUPPKEY;

CREATE OR REPLACE INTERACTIVE TABLE LINEITEM CLUSTER BY (L_SHIPDATE)(
	L_ORDERKEY NUMBER(38,0) NOT NULL,
	L_PARTKEY NUMBER(38,0),
	L_SUPPKEY NUMBER(38,0),
	L_LINENUMBER NUMBER(38,0) NOT NULL,
	L_QUANTITY NUMBER(15,2),
	L_EXTENDEDPRICE NUMBER(15,2),
	L_DISCOUNT NUMBER(15,2),
	L_TAX NUMBER(15,2),
	L_RETURNFLAG VARCHAR(1),
	L_LINESTATUS VARCHAR(1),
	L_SHIPDATE DATE,
	L_COMMITDATE DATE,
	L_RECEIPTDATE DATE,
	L_SHIPINSTRUCT VARCHAR(25),
	L_SHIPMODE VARCHAR(10),
	L_COMMENT VARCHAR(44),
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER) RELY
) AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.LINEITEM ORDER BY L_SHIPDATE;

DROP WAREHOUSE IF EXISTS {{SOLUTION_NAME}}_BENCH_WH_LOAD;
