-- TPC-H standard tables setup (per scale factor)
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS {{SOLUTION_NAME}}_BENCH_DB;
USE DATABASE {{SOLUTION_NAME}}_BENCH_DB;

CREATE SCHEMA IF NOT EXISTS TPCH_SF{{SCALE}};
USE SCHEMA TPCH_SF{{SCALE}};

CREATE OR REPLACE WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_LOAD
  WAREHOUSE_SIZE = '{{LOAD_WH_SIZE}}'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE;

USE WAREHOUSE {{SOLUTION_NAME}}_BENCH_WH_LOAD;

CREATE OR REPLACE TABLE LINEITEM
  CLUSTER BY (L_SHIPDATE)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.LINEITEM;

CREATE OR REPLACE TABLE ORDERS
  CLUSTER BY (O_ORDERDATE)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.ORDERS;

CREATE OR REPLACE TABLE CUSTOMER
  CLUSTER BY (C_CUSTKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.CUSTOMER;

CREATE OR REPLACE TABLE PART
  CLUSTER BY (P_PARTKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PART;

CREATE OR REPLACE TABLE PARTSUPP
  CLUSTER BY (PS_PARTKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PARTSUPP;

CREATE OR REPLACE TABLE SUPPLIER
  CLUSTER BY (S_SUPPKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.SUPPLIER;

CREATE OR REPLACE TABLE NATION
  CLUSTER BY (N_NATIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.NATION;

CREATE OR REPLACE TABLE REGION
  CLUSTER BY (R_REGIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.REGION;

DROP WAREHOUSE IF EXISTS {{SOLUTION_NAME}}_BENCH_WH_LOAD;
